Test with experimental data
peng-lab/BaSiCPy pull request #54
Opened 2022-03-16 00:57 UTC by yfukai

Attempt to make the test with experimental data using `pooch`. Assume #53 to be approved.

2022-05-07 18:37 UTC, Nicholas-Schaub commented
Is this still WIP?

2022-05-08 00:13 UTC, yfukai commented
Yes, this need to wait for #57 .

2022-05-25 07:13 UTC, yfukai commented
This will close #52.

2022-06-13 01:03 UTC, Nicholas-Schaub requested changes
I think this looks good. However, I don't think we should move the inexact_alm to `_deprecated`, and I think we should keep the original code under `fit`. We had previously discussed keeping these for the purposes of reproducing the original results in the paper. If we could maybe place these in a separate section, and then have another setting to select this in addition to `ladmap` and `approximate`, I think that would be best.

2022-06-13 01:41 UTC, yfukai commented on src/basicpy/basicpy.py
> +class FittingMode(Enum):
Thanks! It seems the link is not working. If you wouldn't mind, can you paste the spnippet of the code?

2022-06-13 02:58 UTC, yfukai commented
Closing as we merge PRs to #62.

2022-06-13 02:58 UTC, closed without merging

2022-06-13 03:16 UTC, yfukai commented
Hi, thanks @Nicholas-Schaub for your comment! Actually, the `approximate` fitting method is identical to the original `inexact_alm` (at https://github.com/yfukai/BaSiCpy/tree/reference_implementation/) except for the point that it's implemented in JAX. I compared them in https://github.com/yfukai/BaSiCpy/blob/3d_dct/misc_notebooks/compare_with_reference_impl.ipynb to find the results are close. In my opinion, I think it suffices to keep https://github.com/yfukai/BaSiCpy/tree/reference_implementation/ in the repo and we don't need to maintain the original impl. code (which is basically a copy of Matlab impl. to Python), but let's discuss this tomorrow!

2022-06-13 03:19 UTC, yfukai commented
If it's really necessary I could write the `numpy` impl. of the approximate version, which should give exactly the same results as those of the original ones (but the exact agreement w/ the Matlab version is not guaranteed).